### ISSUE TITLE
error with shrinkwrap and coffee-script and a few other

### ISSUE THREAD

**Issue by DanielRuf** [OSSIndex/auditjs#55]
> Error: ENOENT: no such file or directory, open '/Users/druf/.auditjs/cache/auditjs3x/npm:coffee-script@https:/registry.npmjs.org/coffee-script/-/coffee-script-1.10.0.tgz.json'

```
    "coffee-script": {
      "version": "https://registry.npmjs.org/coffee-script/-/coffee-script-1.10.0.tgz",
      "integrity": "sha1-EpOLz5vhlI+gBvkuDEyegXBRCMA=",
      "dev": true
    },
```

Also `dateformat` has this issue.

```
    "dateformat": {
      "version": "https://registry.npmjs.org/dateformat/-/dateformat-1.0.12.tgz",
      "integrity": "sha1-nxJLZ1lMk3/3BpMuSmQsyo27/uk=",
      "dev": true,
      "requires": {
        "get-stdin": "https://registry.npmjs.org/get-stdin/-/get-stdin-4.0.1.tgz",
        "meow": "https://registry.npmjs.org/meow/-/meow-3.7.0.tgz"
      }
    },
```

Others seem to work, for example `"version": "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz",`

Full stacktrace:
```
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1163:35)
    at Object.putSync (/Users/druf/.config/yarn/global/node_modules/persistent-cache/index.js:72:16)
    at /Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:151:15
    at /Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:179:5
    at Request._callback (/Users/druf/.config/yarn/global/node_modules/auditjs/ossindex.js:107:5)
    at Request.self.callback (/Users/druf/.config/yarn/global/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/druf/.config/yarn/global/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/druf/.config/yarn/global/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by DanielRuf** [comment]
This creates files like
```
    cache/auditjs3x/npm:abbrev@[object Object].json
	cache/auditjs3x/npm:ansi-regex@[object Object].json
	cache/auditjs3x/npm:ansi-styles@[object Object].json
	cache/auditjs3x/npm:aproba@[object Object].json
	cache/auditjs3x/npm:are-we-there-yet@[object Object].json
	cache/auditjs3x/npm:argparse@[object Object].json
	cache/auditjs3x/npm:array-find-index@[object Object].json
	cache/auditjs3x/npm:array-index@[object Object].json
	cache/auditjs3x/npm:asn1@[object Object].json
	cache/auditjs3x/npm:assert-plus@[object Object].json
	cache/auditjs3x/npm:async-foreach@[object Object].json
	cache/auditjs3x/npm:async@[object Object].json
	cache/auditjs3x/npm:async@^1.5.0.json
	cache/auditjs3x/npm:asynckit@[object Object].json
	cache/auditjs3x/npm:aws-sign2@[object Object].json
	cache/auditjs3x/npm:aws4@[object Object].json
	cache/auditjs3x/npm:balanced-match@[object Object].json
	cache/auditjs3x/npm:bcrypt-pbkdf@[object Object].json
	cache/auditjs3x/npm:block-stream@[object Object].json
	cache/auditjs3x/npm:body-parser@[object Object].json
```

So it seems it is a problem with the version parsing.

**Comment by ken-duck** [comment]
Interesting. Thanks for the information!

**Comment by ken-duck** [comment]
I have not seen dependencies defined like this before. Could you provide an example package file which shows where this goes in context?

**Comment by ken-duck** [comment]
I see. That is the package-lock file.

**Comment by ken-duck** [comment]
I have not been able to reproduce this problem. Could you send a package.json file that causes the issue?

If you were running directly against the package-lock.json file, I think the issue may have been resolved in auditjs@3.0.9 (newly published).

**Comment by DanielRuf** [comment]
It happens for example with asyncdesign/webui:

````
auditjs --version
3.0.8
```

```json
{
  "name": "asyncdesign-webui",
  "description": "A mobile-first CSS framework that supports responsive mobile first and fixed desktop layouts.",
  "version": "6.2.1",
  "author": "Levi Keogh",
  "license": "MIT",
  "keywords": [
    "css",
    "sass",
    "responsive",
    "mobile-first",
    "fixed",
    "layout",
    "front-end",
    "framework",
    "web"
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "homepage": "https://asyncdesign.github.io/webui",
  "sass": "src/scss/webui.scss",
  "main": "src/js/webui.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/asyncdesign/webui.git"
  },
  "bugs": {
    "url": "https://github.com/asyncdesign/webui/issues"
  },
  "devDependencies": {
    "grunt": "^1.0.1",
    "grunt-contrib-uglify": "^2.0.0",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-sass": "^2.0.0"
  },
  "dependencies": {
    "node-sass": "^4.5.3"
  },
  "files": [
    "dist",
    "docs",
    "images",
    "src",
    "vendor",
    "gruntfile.js",
    "DEMO-Accordions-Menus-Tabs.html",
    "DEMO-Controls.html",
    "DEMO-Designs.html",
    "DEMO-Forms-Tooltips-Modals-Alerts.html",
    "DEMO-Grids-Layouts.html",
    "DEMO-Positioning.html",
    "DEMO-Shapes.html",
    "DEMO-Transitions.html",
    "DEMO-Typography-Colour-Buttons.html",
    "DEMO-Validation.html",
    "site.css"
  ]
}
```

**Comment by DanielRuf** [comment]
Did an update to 3.0.9 and now I get no errors anymore.
