### ISSUE TITLE
dep.version.indexOf is not a function when checking plyr with yarn

### ISSUE THREAD

**Issue by DanielRuf** [OSSIndex/auditjs#62]
```
CWE-400: Uncontrolled Resource Consumption ('Resource Exhaustion')
The software does not properly restrict the size or amount of resources that are requested or influenced by an actor, which can be used to consume more resources than intended.

ID: 0fa304f3-b464-4e44-b747-1bd5b1922e06
Details: https://ossindex.sonatype.org/vuln/0fa304f3-b464-4e44-b747-1bd5b1922e06
Dependency path: /combohandler/express/send/mime
Dependency path: /combohandler/express/serve-static/send/mime
Dependency path: /yui/request/form-data/mime
------------------------------------------------------------

Unhandled rejection TypeError: dep.version.indexOf is not a function
    at auditPackagesImpl (/Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:157:20)
    at Object.auditPackages (/Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:81:4)
    at /Users/druf/.config/yarn/global/node_modules/auditjs/audit.js:140:49
    at auditPackagesImpl (/Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:176:5)
    at Object.auditPackage (/Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:102:4)
    at /Users/druf/.config/yarn/global/node_modules/auditjs/audit.js:136:41
    at ls.fromTree (/Users/druf/.config/yarn/global/node_modules/npm/lib/ls.js:86:22)
    at /Users/druf/.config/yarn/global/node_modules/npm/lib/ls.js:42:7
    at /Users/druf/.config/yarn/global/node_modules/npm/lib/install/read-shrinkwrap.js:49:14
    at a (/Users/druf/.config/yarn/global/node_modules/npm/node_modules/iferr/iferr.js:3:64)
    at BB.join.then (/Users/druf/.config/yarn/global/node_modules/npm/lib/install/read-shrinkwrap.js:34:16)
    at tryCatcher (/Users/druf/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/druf/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/druf/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/druf/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/druf/.config/yarn/global/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
```

**Comment by DanielRuf** [comment]
I cloned plyr and am currently at

```
commit 5db73b13276bf50357cc98896421318de66ab042 (origin/beta, beta)
Author: Sam Potts <sam@potts.es>
Date:   Sat Mar 17 23:27:40 2018 +1100

    Added buffered getter
```

**Comment by DanielRuf** [comment]
With auditjs@3.0.10:

````
CWE-400: Uncontrolled Resource Consumption ('Resource Exhaustion')
The software does not properly restrict the size or amount of resources that are requested or influenced by an actor, which can be used to consume more resources than intended.

ID: 0090f3c8-2021-48b6-9db0-f15cec8c2017
Details: https://ossindex.sonatype.org/vuln/0090f3c8-2021-48b6-9db0-f15cec8c2017
Dependency path: /gulp/vinyl-fs/glob-stream/glob/minimatch
Dependency path: /gulp/vinyl-fs/glob-stream/minimatch
------------------------------------------------------------

TypeError: dep.version.indexOf is not a function
    at auditPackagesImpl (/Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:179:20)
    at /Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:231:5
    at /Users/druf/.config/yarn/global/node_modules/auditjs/audit-package.js:267:4
    at Request._callback (/Users/druf/.config/yarn/global/node_modules/auditjs/ossindex.js:106:5)
    at Request.self.callback (/Users/druf/.config/yarn/global/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/druf/.config/yarn/global/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/druf/.config/yarn/global/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by DanielRuf** [comment]
[yarn.lock.zip](https://github.com/OSSIndex/auditjs/files/2340703/yarn.lock.zip)

**Comment by DanielRuf** [comment]
Hm, seems after this (after the upgrade?), some (old) files are deleted:

```
...
	deleted:    cache/auditjs3x/npm:jest-mock@19.0.0.json
	deleted:    cache/auditjs3x/npm:jest-mock@20.0.3.json
	deleted:    cache/auditjs3x/npm:jest-mock@21.2.0.json
	deleted:    cache/auditjs3x/npm:jest-mock@22.1.0.json
	deleted:    cache/auditjs3x/npm:jest-mock@22.2.0.json
	deleted:    cache/auditjs3x/npm:jest-mock@22.4.3.json
	deleted:    cache/auditjs3x/npm:jest-regex-util@20.0.3.json
	deleted:    cache/auditjs3x/npm:jest-regex-util@21.2.0.json
	deleted:    cache/auditjs3x/npm:jest-regex-util@22.1.0.json
	deleted:    cache/auditjs3x/npm:jest-regex-util@22.4.3.json
	deleted:    cache/auditjs3x/npm:jest-resolve-dependencies@18.1.0.json
	deleted:    cache/auditjs3x/npm:jest-resolve-dependencies@20.0.3.json
	deleted:    cache/auditjs3x/npm:jest-resolve-dependencies@21.2.0.json
	deleted:    cache/auditjs3x/npm:jest-resolve-dependencies@22.1.0.json
	deleted:    cache/auditjs3x/npm:jest-resolve-dependencies@22.4.3.json
...
```

Only those with `pkg.npm` are left, was there a "breaking" change in the CLI which produces this different behavior?

**Comment by ken-duck** [comment]
There was a bug in the caching mechanism, so the cache paths have changed. I delete the old ones as they would just be noise at this point (never used again).

**Comment by DanielRuf** [comment]
Ah ok, can I simple rename the files or has their content changed too? Should have asked this in another issue as this is not related to the `indexOf` bug.

**Comment by ken-duck** [comment]
Hmm. I don't remember exactly, but I think the content is the same. I am not sure exactly what you are doing, but the auditjs code refreshes these files once a day (its a cache), so technically the files should replace themselves?

**Comment by DanielRuf** [comment]
I just ran auditjs after the self-update.

**Comment by ken-duck** [comment]
About the original issue, it seems that somewhere in the dependency tree there are a couple of dependencies which do not specify a version string, but some sort of object.

```
{
  "pm":"npm",
  "name":"async",
  "version":{"requiredBy":"","missing":true,"optional":false,"depPaths":["/gulp-s3/undefined","/gulp-s3/undefined"]},
  "depPaths":["/gulp-s3/undefined","/gulp-s3/undefined"]
}

{
  "pm":"npm",
  "name":"knox",
  "version":{"requiredBy":"","missing":true,"optional":false},
  "depPaths":["knox@[object Object]"]
}
```

The initial fix for this is to identify these and just indicate there is a problem finding an appropriate version. It will look like this:

```
...
Warning: Unsupported version format for async
Warning: Unsupported version format for knox
...
```

What is curious is in both these cases a version of async and knox ARE found elsewhere in the reportr:

```
[2/699] async 2.6.0   No known vulnerabilities against package/version...
[3/699] knox 0.9.2   No known vulnerabilities against package/version...
```

And these DO seem to be the versions installed, so I think  we don't *actually* lose any information.
