### ISSUE TITLE
Error in getCleanVersion function

### ISSUE THREAD

**Issue by avtrifanov** [OSSIndex/auditjs#71]
There is undefined variable "version" in getCleanVersion function:
```
getCleanVersion = function (range) {
	var re = /([0-9]+)\.([0-9]+)\.([0-9]+)(.*)?/;
	var match = range.match(re);
	if(match != undefined) {
		if (match[4]) {
			return match[1] + "." + match[2] + "." + match[3] + match[4];
		} else {
			return match[1] + "." + match[2] + "." + match[3];
		}
	}
	return version; // This is it
};
```
When "match" is undefined (for example for package with version "1.1") the error happened:
```
/usr/lib/node_modules/auditjs/audit-package.js:140
	return version;
	^

ReferenceError: version is not defined
    at getCleanVersion (/usr/lib/node_modules/auditjs/audit-package.js:140:2)
    at auditPackagesImpl (/usr/lib/node_modules/auditjs/audit-package.js:185:23)
    at Object.auditPackages (/usr/lib/node_modules/auditjs/audit-package.js:82:4)
    at Object.<anonymous> (/usr/lib/node_modules/auditjs/audit.js:188:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

**Comment by ken-duck** [comment]
Ewf. Sorry for delay. Working on a fix now.

**Comment by ken-duck** [comment]
Release 3.1.1 published with a fix.
