### ISSUE TITLE
3.2.1 is not creating cache folder if it does not exist

### ISSUE THREAD

**Issue by bjorngi** [OSSIndex/auditjs#79]
### 3.1.1 w/o cache folder created
```
auditjs --cacheDir /tmp/auditjs --noNode -p package.json
[1/23] classnames 2.2.5   No known vulnerabilities against package/version...
.....
[23/23] rxjs 6.5.2   No known vulnerabilities against package/version...

Audited dependencies: 23, Vulnerable: 0, Ignored: 0
Done in 1.11s.
```

3.2.1 works with cache folder created from 3.1.1, but if cache folder is removed it wont create a new one.

### 3.2.1 w/o cache folder created
```
auditjs -l debug --cacheDir /tmp/auditjs --noNode -p package.json
Error: ENOENT: no such file or directory, open '/tmp/auditjs/cache/auditjs3x/pkg.npm.<package>@2.0.62.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.put (<LOCAL_PATH>/node_modules/auditjs/file-cache.js:89:7)
    at <LOCAL_PATH>/node_modules/auditjs/audit-package.js:213:13
    at <LOCAL_PATH>/node_modules/auditjs/audit-package.js:251:6
    at Request._callback (<LOCAL_PATH>/node_modules/auditjs/ossindex.js:106:5)
    at Request.self.callback (<LOCAL_PATH>/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (<LOCAL_PATH>/node_modules/request/request.js:1161:10)

Audited dependencies: 0, Vulnerable: 0, Ignored: 0

Audited dependencies: 0, Vulnerable: 0, Ignored: 0
Done in 1.24s.
```

**Comment by bjorngi** [comment]
Reproduction: `rm -rf /tmp/auditjs` and run `auditjs -l debug --cacheDir /tmp/auditjs` from project folder.

**Comment by ken-duck** [comment]
Oh duh. I will fix this today (soon). Thanks for letting me know.

**Comment by ken-duck** [comment]
Fixed. I will be running a few additional tests before I close this, but 3.2.2 has been published to npm.

**Comment by bjorngi** [comment]
Great!
Thanks for the great library and quick response time.

Putting it in the `put` function would check if the folder exists for every addition to the cache. Maybe it should be checked once on load instead?

**Comment by ken-duck** [comment]
You are absolutely correct, that is preferable. I panicked ;)

I'll have a cleaner version out shortly (now that I am out of meetings).

**Comment by bjorngi** [comment]
No problem! 

I'm very glad for the quickfix. Finally building green again 👍☑
